import './styles/globals.css'
import './styles/index/index.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>

        </header>
        <main>
          {children}
        </main>
        <footer>

        </footer>
      </body>
    </html>
  )
}
